services:
  api:
    container_name: rag-api
    image: rag-api/rag-api:0.1.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_TIMEOUT=120
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_TRACING=true
      - LANGSMITH_PROJECT=rag-dev
    volumes:
      - ./datasets:/app/datasets
      - ./vectordatabase:/app/vectordatabase
      - ./log:/app/log
    depends_on:
      - ollama
    restart: unless-stopped
    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  ollama:
    image: ollama/ollama:0.32.1
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
